//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BORME.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsers
    {
        public int IdUser { get; set; }
        public string UserLogin { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public bool Active { get; set; }
    }
}
