//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BORME.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int IdCompany { get; set; }
        public string CompanyName { get; set; }
        public int ProvinceCatalogId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreationUserId { get; set; }
        public int ProcessDateId { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual ProcessDates ProcessDates { get; set; }
        public virtual ProvinceCatalog ProvinceCatalog { get; set; }
    }
}
